In [638]:
import pandas as pd
df = pd.read_csv(r"c:\Users\Asus\Downloads\googleplaystore (1).csv")

# def cleanSize(x):
#   if 'M' in x:
#     return float(x.replace('M', ''))
#   return None

# df['Size'] = df['Size'].apply(cleanSize)
# # df['Size'].astype(float)
# df['Size'].unique()

In [639]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

1.What are the top 10 most frequent app categories in the dataset?

In [640]:
df['Category'].value_counts().head(10).reset_index()

          Category  count
0           FAMILY   1972
1             GAME   1144
2            TOOLS    843
3          MEDICAL    463
4         BUSINESS    460
5     PRODUCTIVITY    424
6  PERSONALIZATION    392
7    COMMUNICATION    387
8           SPORTS    384
9        LIFESTYLE    382

2.What is the average rating of apps in each category?

In [641]:
df.groupby('Category')['Rating'].mean().sort_values(ascending=False).reset_index()

               Category     Rating
0                   1.9  19.000000
1                EVENTS   4.435556
2             EDUCATION   4.389032
3        ART_AND_DESIGN   4.358065
4   BOOKS_AND_REFERENCE   4.346067
5       PERSONALIZATION   4.335987
6             PARENTING   4.300000
7                  GAME   4.286326
8                BEAUTY   4.278571
9    HEALTH_AND_FITNESS   4.277104
10             SHOPPING   4.259664
11               SOCIAL   4.255598
12              WEATHER   4.244000
13               SPORTS   4.223511
14         PRODUCTIVITY   4.211396
15       HOUSE_AND_HOME   4.197368
16               FAMILY   4.192272
17          PHOTOGRAPHY   4.192114
18    AUTO_AND_VEHICLES   4.190411
19              MEDICAL   4.189143
20   LIBRARIES_AND_DEMO   4.178462
21       FOOD_AND_DRINK   4.166972
22        COMMUNICATION   4.158537
23               COMICS   4.155172
24   NEWS_AND_MAGAZINES   4.132189
25              FINANCE   4.131889
26        ENTERTAINMENT   4.126174
27             BUSINESS   4.121452
28     TRAVEL_AND_LOCAL   4.109292
29            LIFESTYLE   4.094904
30        VIDEO_PLAYERS   4.063750
31  MAPS_AND_NAVIGATION   4.051613
32                TOOLS   4.047411
33               DATING   3.970769

3.How many apps have a rating greater than 4.5?

In [642]:
(df['Rating']>4.5).sum()

np.int64(1918)

4.Which app category has the highest average rating?

In [643]:
df.groupby('Category')['Rating'].mean().sort_index(ascending=False).head(1)

Category
WEATHER    4.244
Name: Rating, dtype: float64

5.What is the most common app size in the dataset?

In [644]:
def CleanSize(x):
  if 'M' in x:
    return float(x.replace('M', ''))
  elif 'Varies with device' == x:
    return None
  return None

df['Size'] = df['Size'].apply(CleanSize)
commonAppSize = df['Size'].value_counts().head(1)
commonAppSize

Size
11.0    198
Name: count, dtype: int64

6.How many apps are Free vs Paid?

In [645]:
df['Type'].value_counts()

Type
Free    10039
Paid      800
0           1
Name: count, dtype: int64

7. ⁠What is the average price of paid apps?

In [646]:
def CleanPrice(x):
  if '$' in x:
    return float(x.replace('$', ''))
  return None

df['Price'] = df['Price'].apply(CleanPrice)
df[df['Type'] == 'Paid']['Price'].mean()

np.float64(13.920837500000003)

8. ⁠What is the distribution of app installs (e.g., 1K, 10K, 1M+)?

In [647]:
df[df['Installs'].isin(['1,000+', '10,000+', '1,000,000+'])]['Installs'].value_counts()

Installs
1,000,000+    1579
10,000+       1054
1,000+         907
Name: count, dtype: int64

9. ⁠Which category has the highest number of installs overall?

In [648]:
# df.groupby('Category')["Installs"].value_counts()
df.groupby('Category')['Installs'].value_counts().groupby(level=0).sum().sort_values(ascending=False).reset_index()

               Category  count
0                FAMILY   1972
1                  GAME   1144
2                 TOOLS    843
3               MEDICAL    463
4              BUSINESS    460
5          PRODUCTIVITY    424
6       PERSONALIZATION    392
7         COMMUNICATION    387
8                SPORTS    384
9             LIFESTYLE    382
10              FINANCE    366
11   HEALTH_AND_FITNESS    341
12          PHOTOGRAPHY    335
13               SOCIAL    295
14   NEWS_AND_MAGAZINES    283
15             SHOPPING    260
16     TRAVEL_AND_LOCAL    258
17               DATING    234
18  BOOKS_AND_REFERENCE    231
19        VIDEO_PLAYERS    175
20            EDUCATION    156
21        ENTERTAINMENT    149
22  MAPS_AND_NAVIGATION    137
23       FOOD_AND_DRINK    127
24       HOUSE_AND_HOME     88
25   LIBRARIES_AND_DEMO     85
26    AUTO_AND_VEHICLES     85
27              WEATHER     82
28       ART_AND_DESIGN     65
29               EVENTS     64
30            PARENTING     60
31               COMICS     60
32               BEAUTY     53
33                  1.9      1

10. ⁠What is the average number of reviews per app?