In [18]:
import pandas as pd
df = pd.read_csv(r"C:\Users\Asus\Downloads\superstore dataset\Sample - Superstore.csv", encoding='latin1')
# df
# df.shape
df.isna().sum()
# df.duplicated().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [30]:

df['Postal Code'] = df['Postal Code'].fillna(0)

In [31]:
df['Sales'].isna().sum()

np.int64(0)

In [34]:
df.dropna(subset=["Sales"], inplace=True)

In [36]:
df['Profit'].fillna(0, inplace=True)

C:\Users\Asus\AppData\Local\Temp\ipykernel_10484\1321417567.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Profit'].fillna(0, inplace=True)

0        41.9136
1       219.5820
2         6.8714
3      -383.0310
4         2.5164
          ...
9989      4.1028
9990     15.6332
9991     19.3932
9992     13.3200
9993     72.9480
Name: Profit, Length: 9994, dtype: float64

In [47]:
df.groupby('Region')['Sales'].sum()

Region
Central    501239.8908
East       678781.2400
South      391721.9050
West       725457.8245
Name: Sales, dtype: float64

In [48]:
df.groupby('Category')['Sales'].mean()

Category
Furniture          349.834887
Office Supplies    119.324101
Technology         452.709276
Name: Sales, dtype: float64

In [50]:
df.groupby('Category')['Profit'].max()

Category
Furniture          1013.127
Office Supplies    4946.370
Technology         8399.976
Name: Profit, dtype: float64

In [51]:
df.groupby('Category')['Quantity'].sum()

Category
Furniture           8028
Office Supplies    22906
Technology          6939
Name: Quantity, dtype: int64

In [55]:
df.groupby('Category')['Sales'].agg(['mean','max','min','sum'])

                       mean        max    min          sum
Category
Furniture        349.834887   4416.174  1.892  741999.7953
Office Supplies  119.324101   9892.740  0.444  719047.0320
Technology       452.709276  22638.480  0.990  836154.0330

In [9]:
df.groupby('Region')['Profit'].agg(['mean','max','min','sum'])

              mean        max        min          sum
Region
Central  17.092709  8399.9760 -3701.8928   39706.3625
East     32.135808  5039.9856 -6599.9780   91522.7800
South    28.857673  3177.4750 -3839.9904   46749.4303
West     33.849032  6719.9808 -3399.9800  108418.4489

In [43]:
df['Ship Date'] = pd.to_datetime(df['Ship Date'])
df['Ship Date'].dt.month
df['Order Date'] = pd.to_datetime(df["Order Date"])
df['month'] = df['Order Date'].dt.month
df.groupby('month')['Profit'].mean().sort_values(ascending=False)
df['Customer Name'].drop_duplicates

<bound method Series.drop_duplicates of 0            Claire Gute
1            Claire Gute
2        Darrin Van Huff
3         Sean O'Donnell
4         Sean O'Donnell
              ...
9989    Tom Boeckenhauer
9990         Dave Brooks
9991         Dave Brooks
9992         Dave Brooks
9993        Chris Cortes
Name: Customer Name, Length: 9994, dtype: str>

In [49]:
df['Customer Name'].str.split().str[0]

0       Claire
1       Claire
2       Darrin
3         Sean
4         Sean
         ...
9989       Tom
9990      Dave
9991      Dave
9992      Dave
9993     Chris
Name: Customer Name, Length: 9994, dtype: object