**Encodings**
it is a ML preprocessing technique which converts categorical values (strings) into numerical

techinques:
    1.lable encoda
    2.one hot encoder
    3.ordinal encoder
    4.target encoder

1.lable Encoder -
     it is a encoding preprcessing technique which accepts only one columns and encodes the values from 0

In [10]:
# # Lable Encoder
# from sklearn.preprocessing import LabelEncoder
# encodes = LabelEncoder()
# # 1.
# encodes.fit_transform(x_train[column_name])
# # 2.
# encodes.fit_transform(x_train[column_name])
# encodes.transform(x_test[column])
# encodes.transform(x_test[column])

How it works?

col1     selets unique valuse      assigns the value from zero
_____           _____                         a11->0  
|a11|           |a11|                         a12->1
|a12|           |a12|                         a13->2    
|b1 |           |a13|                         b1 ->3
|a13|           |b1 |  
|___|           |___|  

**when to use lable Encoder**
-when we have only catagorical column
-for less unique values
-mostly we use this for target column

**when not to use lable Encoder**
-more than one catagorical column

for transformes model had already learnt the pattern for training data 
so no need to use again fit_transform() directly we can go with transform()

2.One Hot Encoders
it accepts 2d and encodes binary values 

**when to use it**
-when featuers columns are having two or more columns then we use One Hot Encoders
-used when less unique values

**when not to use lable Encoder**

3.Ordinal Encoders
-it encodes the value based on order
-it accepts only 2d
-if we assign the values it assigns directly

In [11]:
# from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
# encoder = OneHotEncoder(handle_unknown="ignore"|"error"(default), sparse_output=True/False default)
# encoder = OrdinalEncoder(catagories = [col_1 order], [col_2 ,order])

# encoder.fit_transform(x_train)4
# encoder.fit_transform(x_train[['col_s']])

<!-- what is target encoder -->
-it is a encoding preprocessing technique which encodes the values based on target column 
-if target column is continoues values then it takes avg 
-if the target column is catagorical values then it takes majority

In [12]:
# from Catagory_encoders import TargetEncoder
# encoder = TargetEncoder()
# encoders fit.fit_transform(x_train)

In [13]:
import pandas as pd
import numpy as np
# data = pd.DataFrame({'age':['ten', 'twenty', 'eleven', 'fifty', 'five'], 'salary':['1k', '2k', '3k','1k', '5k'],'study_hour':['one','two','one','four','five'],'target':[10,20,30,40,50]})
n_rows=1000
data = {
    'color': np.random.choice(['red', 'blue', 'green'], n_rows),
    'size': np.random.choice(['small', 'medium', 'large'], n_rows),
    'material': np.random.choice(['plastic', 'metal', 'wood'], n_rows),
    'price': np.random.randint(10,500, n_rows)
}
df=pd.DataFrame(data)
df

     color    size material  price
0      red   small     wood    311
1      red   large    metal    200
2    green   small    metal    163
3      red  medium     wood    263
4    green   large  plastic    402
..     ...     ...      ...    ...
995  green   large  plastic    130
996   blue  medium    metal    399
997    red  medium  plastic    418
998   blue  medium  plastic     28
999    red  medium     wood    371

[1000 rows x 4 columns]

In [14]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder
# from category_encoders import TargetEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression


X=df.drop(columns='price')
y=df.price
x_train,x_test,y_train,y_test = train_test_split(X,y,train_size=0.2,random_state=42)

In [24]:
# label_encoder = LabelEncoder()
# update_Xtrain = label_encoder.fit_transform(x_train)

In [20]:
# OneHot encoder
encoder = OneHotEncoder()
encoder.fit_transform(x_train)
#roarray()
values = encoder.fit_transform(x_train)
values=values.toarray()
columns = encoder.get_feature_names_out()
pd.DataFrame(values, columns=columns)

,color_blue,color_green,color_red,size_large,size_medium,size_small,material_metal,material_plastic,material_wood
0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
3,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
4,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
195,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
196,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
197,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
198,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
199,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0